/*
 * jPOS Project [http://jpos.org]
 * Copyright (C) 2000-2026 jPOS Software SRL
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

package org.jpos.iso;

import org.jpos.transaction.TxnId;

import java.util.Optional;

/**
 * Encodes and decodes the ISO 8583 Transaction Life Cycle Identification Data
 * (DE-021).
 *
 * <p>DE-021 is a 19-byte constructed field that correlates related messages
 * across a transaction's full life cycle—authorization, financial presentment,
 * reversal, and chargeback.</p>
 *
 * <h2>Wire layout</h2>
 * <pre>
 *  Bytes  Notation     Sub-field
 *  1       AN1 (ASCII)  Life cycle support indicator
 *  2–16   AN15 (ASCII)  Life cycle trace identifier
 *  17–18  N2 (BCD)     Life cycle transaction sequence number
 *  19–22  N4 (BCD)     Life cycle authentication token
 * </pre>
 *
 * <h2>jPOS TxnId integration</h2>
 * <p>When jPOS originates a transaction, the trace identifier is populated from
 * a {@link TxnId} via its base-36 {@link TxnId#toRrn()} form, right-padded with
 * spaces to 15 characters. On inbound messages, {@link #txnId()} attempts to
 * reverse this mapping; it returns an empty {@link Optional} when the trace
 * identifier does not represent a {@code TxnId} (e.g. when received from an
 * external network with its own trace ID scheme).</p>
 *
 * <h2>Usage — outbound (originates authorization)</h2>
 * <pre>
 * byte[] de21 = LifeCycleId.builder()
 *     .supportIndicator(mti)        // derives '1' for 1xx, '2' for 2xx, etc.
 *     .traceId(txnId)               // uses txnId.toRrn(), padded to 15 chars
 *     .build()
 *     .pack();
 * msg.set(new ISOBinaryField(21, de21));
 * </pre>
 *
 * <h2>Usage — outbound (financial presentment echoing prior auth)</h2>
 * <pre>
 * LifeCycleId authLC = LifeCycleId.unpack(authMsg.getBytes(21));
 * byte[] de21 = authLC.toBuilder()
 *     .sequenceNumber(seq)
 *     .authToken(tokenFromAuthResponse)
 *     .build()
 *     .pack();
 * </pre>
 *
 * <h2>Usage — inbound (from external network)</h2>
 * <pre>
 * LifeCycleId lc = LifeCycleId.unpack(msg.getBytes(21));
 * lc.txnId().ifPresent(t -> ctx.put("TXNID", t));
 * String rawTrace = lc.traceIdentifier();
 * </pre>
 *
 * @see <a href="https://jpos.org/doc/jPOS-CMF.pdf">jPOS CMF Specification — DE-021</a>
 */
public final class LifeCycleId {

    /** Wire length of the full DE-021 field in bytes. */
    public static final int WIRE_LENGTH = 19;

    /** Maximum trace identifier length in characters. */
    public static final int TRACE_ID_LENGTH = 15;

    private static final int SEQ_OFFSET  = 16;   // 1 + 15 = 16
    private static final int AUTH_OFFSET = 17;   // 16 + 1 (N2 = 2 digits BCD = 1 byte)

    private final char   supportIndicator;
    private final String traceIdentifier;
    private final int    sequenceNumber;
    private final int    authToken;

    private LifeCycleId(Builder b) {
        this.supportIndicator = b.supportIndicator;
        this.traceIdentifier  = b.traceIdentifier;
        this.sequenceNumber   = b.sequenceNumber;
        this.authToken        = b.authToken;
    }

    // ── Accessors ─────────────────────────────────────────────────────────────

    /**
     * Returns the life cycle support indicator character.
     * {@code '1'} indicates the identifier was first assigned during an
     * authorization message; {@code '2'} during a financial presentment.
     *
     * @return support indicator
     */
    public char supportIndicator() {
        return supportIndicator;
    }

    /**
     * Returns the raw 15-character life cycle trace identifier.
     *
     * @return trace identifier
     */
    public String traceIdentifier() {
        return traceIdentifier;
    }

    /**
     * Attempts to parse the trace identifier as a jPOS {@link TxnId}.
     *
     * <p>Returns a non-empty {@link Optional} when the trimmed trace identifier
     * was produced by {@link TxnId#toRrn()}. Returns empty for identifiers
     * generated by other systems.</p>
     *
     * @return optional TxnId
     */
    public Optional<TxnId> txnId() {
        try {
            return Optional.of(TxnId.fromRrn(traceIdentifier.trim()));
        } catch (Exception e) {
            return Optional.empty();
        }
    }

    /**
     * Returns the life cycle transaction sequence number.
     * Zero when not assigned.
     *
     * @return sequence number
     */
    public int sequenceNumber() {
        return sequenceNumber;
    }

    /**
     * Returns the life cycle authentication token assigned by the card issuer.
     * Zero when not yet assigned or when omitted by mutual agreement.
     *
     * @return authentication token
     */
    public int authToken() {
        return authToken;
    }

    // ── Pack / Unpack ─────────────────────────────────────────────────────────

    /**
     * Serializes this life cycle identifier to the DE-021 wire format.
     *
     * @return 19-byte wire representation
     */
    public byte[] pack() {
        byte[] buf = new byte[WIRE_LENGTH];
        buf[0] = (byte) supportIndicator;
        byte[] trace = traceIdentifier.getBytes(java.nio.charset.StandardCharsets.ISO_8859_1);
        System.arraycopy(trace, 0, buf, 1, TRACE_ID_LENGTH);
        // Sequence number: N2 in cmf.xml = 2 BCD digits = 1 byte
        ISOUtil.str2bcd(String.format("%02d", sequenceNumber), false, buf, SEQ_OFFSET);
        // Auth token: N4 in cmf.xml = 4 BCD digits = 2 bytes
        ISOUtil.str2bcd(String.format("%04d", authToken), false, buf, AUTH_OFFSET);
        return buf;
    }

    /**
     * Deserializes DE-021 bytes into a {@code LifeCycleId}.
     *
     * @param data 19-byte DE-021 field content
     * @return parsed life cycle identifier
     * @throws ISOException when the byte array is null, empty, or too short
     */
    public static LifeCycleId unpack(byte[] data) throws ISOException {
        if (data == null || data.length < WIRE_LENGTH) {
            throw new ISOException("DE-021 requires exactly " + WIRE_LENGTH + " bytes, got "
                    + (data == null ? "null" : data.length));
        }
        char indicator = (char) (data[0] & 0xFF);
        String trace   = new String(data, 1, TRACE_ID_LENGTH,
                java.nio.charset.StandardCharsets.ISO_8859_1);
        int seq   = Integer.parseInt(ISOUtil.bcd2str(data, SEQ_OFFSET,  2, false));
        int token = Integer.parseInt(ISOUtil.bcd2str(data, AUTH_OFFSET, 4, false));
        return new Builder()
                .supportIndicator(indicator)
                .traceId(trace)
                .sequenceNumber(seq)
                .authToken(token)
                .build();
    }

    // ── Builder ───────────────────────────────────────────────────────────────

    /**
     * Creates a new {@link Builder} pre-populated with this instance's values.
     * Useful for constructing a financial presentment that echoes an authorization's
     * life cycle identifier.
     *
     * @return builder initialized from this instance
     */
    public Builder toBuilder() {
        return new Builder()
                .supportIndicator(supportIndicator)
                .traceId(traceIdentifier)
                .sequenceNumber(sequenceNumber)
                .authToken(authToken);
    }

    /**
     * Returns a new empty builder.
     *
     * @return builder
     */
    public static Builder builder() {
        return new Builder();
    }

    /**
     * Derives the life cycle support indicator character from an ISO 8583 MTI.
     * Returns the first digit of the MTI's class component (position 1, 0-indexed).
     *
     * <p>Examples: {@code "0100"} → {@code '1'}, {@code "0200"} → {@code '2'},
     * {@code "0420"} → {@code '4'}.</p>
     *
     * @param mti 3- or 4-character ISO 8583 MTI string
     * @return support indicator character
     * @throws IllegalArgumentException when the MTI is null or too short
     */
    public static char supportIndicatorForMTI(String mti) {
        if (mti == null || mti.length() < 2) {
            throw new IllegalArgumentException("MTI too short: " + mti);
        }
        // For a 4-char MTI (e.g. "0100"), class is digit at index 1.
        // For a 3-char MTI used in CMF shorthand (e.g. "100"), class is digit at index 0.
        return mti.length() >= 4 ? mti.charAt(1) : mti.charAt(0);
    }

    // ─────────────────────────────────────────────────────────────────────────

    /**
     * Builder for {@link LifeCycleId}.
     */
    public static final class Builder {
        private char   supportIndicator = '0';
        private String traceIdentifier  = padTrace("");
        private int    sequenceNumber   = 0;
        private int    authToken        = 0;

        private Builder() {}

        /**
         * Sets the support indicator from a literal character.
         *
         * @param indicator support indicator character
         * @return this builder
         */
        public Builder supportIndicator(char indicator) {
            this.supportIndicator = indicator;
            return this;
        }

        /**
         * Derives the support indicator from an ISO 8583 MTI string.
         *
         * @param mti ISO 8583 MTI (3 or 4 characters)
         * @return this builder
         */
        public Builder supportIndicator(String mti) {
            this.supportIndicator = supportIndicatorForMTI(mti);
            return this;
        }

        /**
         * Sets the trace identifier from a jPOS {@link TxnId}.
         * Uses {@link TxnId#toRrn()}, right-padded with spaces to 15 characters.
         *
         * @param txnId jPOS transaction identifier
         * @return this builder
         */
        public Builder traceId(TxnId txnId) {
            this.traceIdentifier = padTrace(txnId.toRrn());
            return this;
        }

        /**
         * Sets the trace identifier from a raw string.
         * MUST be at most 15 characters; shorter values are right-padded with spaces.
         *
         * @param trace trace identifier string
         * @return this builder
         * @throws IllegalArgumentException when the string exceeds 15 characters
         */
        public Builder traceId(String trace) {
            if (trace != null && trace.length() > TRACE_ID_LENGTH) {
                throw new IllegalArgumentException(
                        "Trace identifier exceeds " + TRACE_ID_LENGTH + " characters: " + trace);
            }
            this.traceIdentifier = padTrace(trace == null ? "" : trace);
            return this;
        }

        /**
         * Sets the life cycle transaction sequence number.
         *
         * @param seq sequence number (0–9999)
         * @return this builder
         */
        public Builder sequenceNumber(int seq) {
            this.sequenceNumber = seq;
            return this;
        }

        /**
         * Sets the life cycle authentication token.
         *
         * @param token authentication token (0–9999)
         * @return this builder
         */
        public Builder authToken(int token) {
            this.authToken = token;
            return this;
        }

        /**
         * Builds the {@link LifeCycleId}.
         *
         * @return new LifeCycleId
         */
        public LifeCycleId build() {
            return new LifeCycleId(this);
        }

        private static String padTrace(String s) {
            if (s.length() == TRACE_ID_LENGTH) return s;
            return String.format("%-" + TRACE_ID_LENGTH + "s", s);
        }
    }

    @Override
    public String toString() {
        return "LifeCycleId{indicator=" + supportIndicator
                + ", trace='" + traceIdentifier.trim() + "'"
                + ", seq=" + sequenceNumber
                + ", token=" + authToken + "}";
    }
}
