=== SendResponse

The `org.jpos.transaction.participant.SendResponse` can be used
to provide responses to a given source. It looks for a `SOURCE`
property and a `RESPONSE` property in the Context and if both
are present, and the source is connected, it sends back the response.

.SendResponse Configuration Properties
[cols="1,2,2", options="header"]
|=============================================================================
|Property  | Description                                 | Default Value
|source    | `ISOSource` used to send back the response  | `SOURCE` 
|request   | The request `ISOMsg`                        | `REQUEST` 
|response  | A response `ISOMsg`                         | `RESPONSE` 
|header-strategy | Header handling                       | `PRESERVE_RESPONSE`
|=============================================================================

The `header-strategy` is used to define how to handle the message's header.
It supports the following values:

* `PRESERVE_RESPONSE` (default) use the response's header
* `PRESERVE_ORIGINAL` use the request's header
* `SET_TO_NULL` ditto - sets the response header to null

[NOTE]
======
As a safety net, the `SendResponse` participant verifies that there is
no entry in the Context under the name `TX` (typically used to store a
JDBC/DB transaction. This is an arbitrary convention, we want to make
sure that transactions are committed to disk before actually sending
back responses.
======

