[[configuration]]

== Configuration

*org.jpos.core.Configuration* is a general purpose property container 
extensively used by jPOS components. 

The Configuration interface looks like this: 

[source,java]
----

   package org.jpos.core;

   public interface Configuration {
     public void put (String name, Object value);
     public String get (String propertyName);
     public String get (String propertyName, String defaultValue);
     public String[] getAll  (String propertyName);
     public int[] getInts  (String propertyName);
     public long[] getLongs (String propertyName);
     public double[] getDoubles (String propertyName);
     public boolean[] getBooleans (String propertyName);
     public int getInt (String propertyName);
     public int getInt (String propertyName, int defaultValue);
     public long getLong (String propertyName);
     public long getLong (String propertyName, long defaultValue);
     public double getDouble (String propertyName);
     public double getDouble (String propertyName, double defaultValue);
     public boolean getBoolean (String propertyName);
     public boolean getBoolean (String propertyName, boolean defaultValue);
   }
----

Having our own Configuration interface lets us implement it in different ways.
We have a very little class called SimpleConfiguration backed by a
java.util.Properties, but nothing prevents us from creating a more
sophisticated Configuration object capable of providing dynamic data (such as
an SQLConfiguration, JavaSpacesConfiguration and the like). 

jPOS-EE implements a SysConfigConfiguration that reads objects from its +sysconfig+ SQL table.

We also have a very simple interface called Configurable: 

[source,java]
----

   package org.jpos.core;

   public interface Configuration {
     public void setConfiguration (Configuration cfg) 
        throws ConfigurationException;
   }
  
----

Later, while looking at the Q2 application we'll see that Q2 pushes a
configuration object by calling the +setConfiguration+ method on
+Configurable+ objects.

[source,xml]
----
    <object name="myObject" class="com.mycompany.MyObject">
      <property name="myProperty" value="any Value" />
    </object>
----

Should +com.mycompany.MyObject"+ implement +Configurable+, Q2 would call its  +setConfiguration()+ method 
providing access to the underlying +myProperty+ property. 

It's interesting to note that Q2 provides the ability to have array of
properties under the same name, i.e: 

[source,xml]
----

    <object name="myObject" class="com.mycompany.MyObject">
     <property name="myProperty" value="Value A" />
     <property name="myProperty" value="Value B" />
     <property name="myProperty" value="Value C" />
    </object>
  
----

where one can call handy methods like  +String\[\] getAll(String)+. 

+setConfiguration(Configuration cfg)+ can check the Configuration object and might 
throw a +ConfigurationException+ in case a required property is not present or 
is invalid. 

[TIP]
=====
SimpleConfiguration recognizes and de-reference properties with the
format: `${xxx}` and search for a system property, or operating system
environment variable under the `xxx` name. 

The format `$sys{xxx}` de-reference just from system properties, and
`$env{xxx}` just from the operating system environment. 

In the rare case where a value with the format `${...}` is required, the
`$verb{${...}}` format (verbatim) can be used.
=====

