/**
 * ISO 8583 v1987 BINARY Packager
 *
 * @author apr@cs.com.uy
 * @version $Id$
 * @see ISOPackager
 * @see ISOBasePackager
 * @see ISOComponent
 */

/*
 * $Log$
 * Revision 1.2  1998/12/11 14:06:25  apr
 * Added 'pad' parameter en 'IFB_[L*]NUM*' y 'IFB_AMOUNT'
 *
 * Revision 1.1  1998/11/09 23:40:20  apr
 * *** empty log message ***
 *
 */

package uy.com.cs.jpos.iso;

import java.util.*;

public class ISO87BPackager extends ISOBasePackager {
	private static final boolean pad = false;
	protected ISOFieldPackager fld[] = {
			new IFB_NUMERIC	(  4, "MESSAGE TYPE INDICATOR", pad),
			new IFB_BITMAP	( 16, "BIT MAP"),
			new IFB_LLNUM	( 19, "PAN - PRIMARY ACCOUNT NUMBER", pad),
			new IFB_NUMERIC	(  6, "PROCESSING CODE", pad),
			new IFB_NUMERIC	( 12, "AMOUNT, TRANSACTION", pad),
			new IFB_NUMERIC	( 12, "AMOUNT, SETTLEMENT", pad),
			new IFB_NUMERIC	( 12, "AMOUNT, CARDHOLDER BILLING", pad),
			new IFB_NUMERIC	( 10, "TRANSMISSION DATE AND TIME", pad),
			new IFB_NUMERIC	(  8, "AMOUNT, CARDHOLDER BILLING FEE", pad),
			new IFB_NUMERIC	(  8, "CONVERSION RATE, SETTLEMENT", pad),
			new IFB_NUMERIC	(  8, "CONVERSION RATE, CARDHOLDER BILLING", pad),
			new IFB_NUMERIC	(  6, "SYSTEM TRACE AUDIT NUMBER", pad),
			new IFB_NUMERIC	(  6, "TIME, LOCAL TRANSACTION", pad),
			new IFB_NUMERIC	(  4, "DATE, LOCAL TRANSACTION", pad),
			new IFB_NUMERIC	(  4, "DATE, EXPIRATION", pad),
			new IFB_NUMERIC	(  4, "DATE, SETTLEMENT", pad),
			new IFB_NUMERIC	(  4, "DATE, CONVERSION", pad),
			new IFB_NUMERIC	(  4, "DATE, CAPTURE", pad),
			new IFB_NUMERIC	(  4, "MERCHANTS TYPE", pad),
			new IFB_NUMERIC	(  3, "ACQUIRING INSTITUTION COUNTRY CODE", pad),
			new IFB_NUMERIC	(  3, "PAN EXTENDED COUNTRY CODE", pad),
			new IFB_NUMERIC	(  3, "FORWARDING INSTITUTION COUNTRY CODE", pad),
			new IFB_NUMERIC	(  3, "POINT OF SERVICE ENTRY MODE", pad),
			new IFB_NUMERIC	(  3, "CARD SEQUENCE NUMBER", pad),
			new IFB_NUMERIC	(  3, "NETWORK INTERNATIONAL IDENTIFIEER", pad),
			new IFB_NUMERIC	(  2, "POINT OF SERVICE CONDITION CODE", pad),
			new IFB_NUMERIC	(  2, "POINT OF SERVICE PIN CAPTURE CODE", pad),
			new IFB_NUMERIC	(  1, "AUTHORIZATION IDENTIFICATION RESP LEN", pad),
			new IFB_AMOUNT	(  9, "AMOUNT, TRANSACTION FEE", pad),
			new IFB_AMOUNT	(  9, "AMOUNT, SETTLEMENT FEE", pad),
			new IFB_AMOUNT	(  9, "AMOUNT, TRANSACTION PROCESSING FEE", pad),
			new IFB_AMOUNT	(  9, "AMOUNT, SETTLEMENT PROCESSING FEE", pad),
			new IFB_LLNUM	( 11, "ACQUIRING INSTITUTION IDENT CODE", pad),
			new IFB_LLNUM	( 11, "FORWARDING INSTITUTION IDENT CODE", pad),
			new IFB_LLCHAR	( 28, "PAN EXTENDED"),
			new IFB_LLNUM	( 37, "TRACK 2 DATA", pad),
			new IFB_LLLCHAR	(104, "TRACK 3 DATA"),
			new IF_CHAR		( 12, "RETRIEVAL REFERENCE NUMBER"),
			new IF_CHAR		(  6, "AUTHORIZATION IDENTIFICATION RESPONSE"),
			new IF_CHAR		(  2, "RESPONSE CODE"),
			new IF_CHAR		(  3, "SERVICE RESTRICTION CODE"),
			new IF_CHAR		(  8, "CARD ACCEPTOR TERMINAL IDENTIFICACION"),
			new IF_CHAR		( 15, "CARD ACCEPTOR IDENTIFICATION CODE" ),
			new IF_CHAR		( 40, "CARD ACCEPTOR NAME/LOCATION"),
			new IFB_LLCHAR	( 25, "ADITIONAL RESPONSE DATA"),
			new IFB_LLCHAR	( 76, "TRACK 1 DATA"),
			new IFB_LLLCHAR	(999, "ADITIONAL DATA - ISO"),
			new IFB_LLLCHAR	(999, "ADITIONAL DATA - NATIONAL"),
			new IFB_LLLCHAR	(999, "ADITIONAL DATA - PRIVATE"),
			new IF_CHAR		(  3, "CURRENCY CODE, TRANSACTION"),
			new IF_CHAR		(  3, "CURRENCY CODE, SETTLEMENT"),
			new IF_CHAR		(  3, "CURRENCY CODE, CARDHOLDER BILLING"   ),
			new IFB_BINARY	(  8, "PIN DATA"   ),
			new IFB_NUMERIC	( 16, "SECURITY RELATED CONTROL INFORMATION", pad),
			new IFB_LLLCHAR	(120, "ADDITIONAL AMOUNTS"),
			new IFB_LLLCHAR	(999, "RESERVED ISO"),
			new IFB_LLLCHAR	(999, "RESERVED ISO"),
			new IFB_LLLCHAR	(999, "RESERVED NATIONAL"),
			new IFB_LLLCHAR	(999, "RESERVED NATIONAL"),
			new IFB_LLLCHAR	(999, "RESERVED NATIONAL"),
			new IFB_LLLCHAR	(999, "RESERVED PRIVATE"),
			new IFB_LLLCHAR	(999, "RESERVED PRIVATE"),
			new IFB_LLLCHAR	(999, "RESERVED PRIVATE"),
			new IFB_LLLCHAR	(999, "RESERVED PRIVATE"),
			new IFB_BINARY	(  8, "MESSAGE AUTHENTICATION CODE FIELD"),
			new IFB_BINARY	(  1, "BITMAP, EXTENDED"),
			new IFB_NUMERIC	(  1, "SETTLEMENT CODE", pad),
			new IFB_NUMERIC	(  2, "EXTENDED PAYMENT CODE", pad),
			new IFB_NUMERIC	(  3, "RECEIVING INSTITUTION COUNTRY CODE", pad),
			new IFB_NUMERIC	(  3, "SETTLEMENT INSTITUTION COUNTRY CODE", pad),
			new IFB_NUMERIC	(  3, "NETWORK MANAGEMENT INFORMATION CODE", pad),
			new IFB_NUMERIC	(  4, "MESSAGE NUMBER", pad),
			new IFB_NUMERIC	(  4, "MESSAGE NUMBER LAST", pad),
			new IFB_NUMERIC	(  6, "DATE ACTION", pad),
			new IFB_NUMERIC	( 10, "CREDITS NUMBER", pad),
			new IFB_NUMERIC	( 10, "CREDITS REVERSAL NUMBER", pad),
			new IFB_NUMERIC	( 10, "DEBITS NUMBER", pad),
			new IFB_NUMERIC	( 10, "DEBITS REVERSAL NUMBER", pad),
			new IFB_NUMERIC	( 10, "TRANSFER NUMBER", pad),
			new IFB_NUMERIC	( 10, "TRANSFER REVERSAL NUMBER", pad),
			new IFB_NUMERIC	( 10, "INQUIRIES NUMBER", pad),
			new IFB_NUMERIC	( 10, "AUTHORIZATION NUMBER", pad),
			new IFB_NUMERIC	( 12, "CREDITS, PROCESSING FEE AMOUNT", pad),
			new IFB_NUMERIC	( 12, "CREDITS, TRANSACTION FEE AMOUNT", pad),
			new IFB_NUMERIC	( 12, "DEBITS, PROCESSING FEE AMOUNT", pad),
			new IFB_NUMERIC	( 12, "DEBITS, TRANSACTION FEE AMOUNT", pad),
			new IFB_NUMERIC	( 16, "CREDITS, AMOUNT", pad),
			new IFB_NUMERIC	( 16, "CREDITS, REVERSAL AMOUNT", pad),
			new IFB_NUMERIC	( 16, "DEBITS, AMOUNT", pad),
			new IFB_NUMERIC	( 16, "DEBITS, REVERSAL AMOUNT", pad),
			new IFB_NUMERIC	( 42, "ORIGINAL DATA ELEMENTS", pad),
			new IF_CHAR		(  1, "FILE UPDATE CODE"),
			new IF_CHAR		(  2, "FILE SECURITY CODE"),
			new IF_CHAR		(  6, "RESPONSE INDICATOR"),
			new IF_CHAR		(  7, "SERVICE INDICATOR"),
			new IF_CHAR		( 42, "REPLACEMENT AMOUNTS"),
			new IFB_BINARY	( 16, "MESSAGE SECURITY CODE"),
			new IFB_AMOUNT	( 17, "AMOUNT, NET SETTLEMENT", pad),
			new IF_CHAR	    ( 25, "PAYEE"),
			new IFB_LLNUM	( 11, "SETTLEMENT INSTITUTION IDENT CODE", pad),
			new IFB_LLNUM	( 11, "RECEIVING INSTITUTION IDENT CODE", pad),
			new IFB_LLCHAR	( 17, "FILE NAME"),
			new IFB_LLCHAR	( 28, "ACCOUNT IDENTIFICATION 1"),
			new IFB_LLCHAR	( 28, "ACCOUNT IDENTIFICATION 2"),
			new IFB_LLLCHAR	(100, "TRANSACTION DESCRIPTION"),
			new IFB_LLLCHAR	(999, "RESERVED ISO USE"), 
			new IFB_LLLCHAR	(999, "RESERVED ISO USE"), 
			new IFB_LLLCHAR	(999, "RESERVED ISO USE"), 
			new IFB_LLLCHAR	(999, "RESERVED ISO USE"), 
			new IFB_LLLCHAR	(999, "RESERVED ISO USE"), 
			new IFB_LLLCHAR	(999, "RESERVED ISO USE"), 
			new IFB_LLLCHAR	(999, "RESERVED ISO USE"), 
			new IFB_LLLCHAR	(999, "RESERVED NATIONAL USE"),
			new IFB_LLLCHAR	(999, "RESERVED NATIONAL USE"),
			new IFB_LLLCHAR	(999, "RESERVED NATIONAL USE"   ),
			new IFB_LLLCHAR	(999, "RESERVED NATIONAL USE"),
			new IFB_LLLCHAR	(999, "RESERVED NATIONAL USE"  ),
			new IFB_LLLCHAR	(999, "RESERVED NATIONAL USE"),
			new IFB_LLLCHAR	(999, "RESERVED NATIONAL USE"),
			new IFB_LLLCHAR	(999, "RESERVED NATIONAL USE"),
			new IFB_LLLCHAR	(999, "RESERVED PRIVATE USE"),
			new IFB_LLLCHAR	(999, "RESERVED PRIVATE USE"),
			new IFB_LLLCHAR	(999, "RESERVED PRIVATE USE"),
			new IFB_LLLCHAR	(999, "RESERVED PRIVATE USE"),
			new IFB_LLLCHAR	(999, "RESERVED PRIVATE USE"),
			new IFB_LLLCHAR	(999, "RESERVED PRIVATE USE"),
			new IFB_LLLCHAR	(999, "RESERVED PRIVATE USE"),
			new IFB_LLLCHAR	(999, "RESERVED PRIVATE USE"),
			new IFB_BINARY	(  8, "MAC 2")
		};
	public ISO87BPackager() {
		super();
		setFieldPackager(fld);
	}
}
