[[iso8583_intro]]

== About ISO-8583
We assume the reader is familiar with the ISO-8583 standard.

For starters, you can take a look at the Wikipedia
http://en.wikipedia.org/wiki/ISO_8583[ISO_8583] page and the <<iso8583>>
of this document, but for any serious work you need to get a copy
of the standard from http://www.iso.org.

This is a high level standard, and vendors have implemented it in slightly
different ways. You also need the protocol specifications for your
particular interchange.

If you are starting a new payments application and you have full control over
your spec, you may want to consider using the ISO-8583 v2003 based jPOS Common
Message Format described in http://jpos.org/doc/jPOS-CMF.pdf.

[TIP]
=====
The jPOS-CMF is an open source project, you can get the DocBook sources
in the jPOS Github reporitory at http://github.com/jPOS/jPOS-CMF and
modify it to fit your needs. This is an open spec, we expect institutions
using it to get in touch with us in order to improve it.
=====


