== Using jPOS

You don't have to build jPOS in order to use it in your projects,
although you are welcome to try and build it (see <<building>>) for 
learning purposes or if you want to contribute to the project.

jPOS produces Maven compatible +poms+ and regularly publishes releases
to http://search.maven.org[Maven Central].

If you want to use it from Maven, you can add this dependency to your +pom+:

Here is a sample POM
[source,xml]
-----------------------------------------------------------------------------
<dependency>
    <groupId>org.jpos</groupId>
    <artifactId>jpos</artifactId>
    <version>1.9.8</version>
</dependency>
-----------------------------------------------------------------------------

jPOS uses a couple dependencies not available in Maven central, so you need to add
the following repositories:

* http://download.oracle.com/maven (required by Berkeley DB Java Edition)
* http://jline.sourceforge.net/m2repo (required by jline)

[NOTE]
======
We publish SNAPSHOT daily builds (i.e. version 1.9.9-SNAPSHOT) to 
the http://jpos.org/maven[jPOS Maven repository].
======

if you use Gradle, you can configure:

[source,groovy]
-----------------------------------------------------------------------------
repositories {
    mavenLocal()
    mavenCentral()
    mavenRepo name: 'oracle', url: "http://download.oracle.com/maven"
    mavenRepo name: 'jline', url: "http://jline.sourceforge.net/m2repo"
    mavenRepo url: "http://jpos.org/maven"
}

dependencies {
    compile group:'org.jpos', name:'jpos', version:'1.9.8+'
    testCompile group:'junit', name:'junit', version:'4.8.2'
}
-----------------------------------------------------------------------------


[TIP]
=====
If you're building a jPOS application, the easiest way is to clone the
http://github.com/jpos/jPOS-template[jPOS Template] 
project and take it from there.
=====

